version: '3.8'
services:
  backend:
    build:
      context: .
      dockerfile: docker/Dockerfile
    restart: unless-stopped
  frontend:
    build:
      context: .
      dockerfile: docker/front.dockerfile
    depends_on:
      - backend
    restart: unless-stopped
